#!/bin/sh
#SBATCH --job-name=uniprot_data_curation                         # Job name
#SBATCH --mail-type=BEGIN,END,FAIL                              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=hb1115@york.ac.uk                           # Where to send mail  
#SBATCH --ntasks=1                                              # Run a single task...
#SBATCH --cpus-per-task=1                                       # ...with 16 cores
#--partition=week                                               # To prevent exceeding time limit 
#SBATCH --mem=16gb                                              # Job memory request
#SBATCH --time=48:00:00                                         # Time limit hrs:min:sec
#SBATCH --output=improved_uniprot_curation_%j.log               # Standard output and error log
#SBATCH --account=chem-structglyco-2019

module purge

module load devel/CMake/3.16.4-GCCcore-9.3.0
module load lang/Python/3.8.2-GCCcore-9.3.0

cmake --version || "CMake is not found!. Install CMake then re-run this script " || exit 3
gcc --version  || "GCC is not found!. Install GCC then re-run this script " || exit 3

GCC="$(which gcc)"
GPLUSPLUS="$(which g++)"
echo "GCC: $GCC"
echo "GCC: $GPLUSPLUS"
GFORTRAN="$(which gfortran)"
echo "GFORTRAN: $GFORTRAN"
Threads="$(nproc --all)"

export CC=$GCC
export CXX=$GPLUSPLUS
export FC=$GFORTRAN

mainDir=/users/hb1115/scratch/PDB_anal
cd $mainDir
cd $mainDir/privateer
privateerDir=$PWD
cd $privateerDir
source $privateerDir/pvtpython/bin/activate
source $privateerDir/ccp4.envsetup-sh
cd $mainDir/quick_python_utility_scripts
git stash
git pull
cd $mainDir/quick_python_utility_scripts/find_models_for_uniprotID
scriptDir=$PWD
rm -rf output

echo Current working directory is `pwd`
echo Running job on host:
echo -e '\t'`hostname` at `date`
echo $SLURM_CPUS_ON_NODE CPU cores available
echo
echo Privateer directory is located at $scriptDir

pip3 install -r requirements.txt
pip install -r requirements.txt
python3 --version
which python3

python3 $scriptDir/main.py
cd $scriptDir
ls
git status

echo Job completed at `date`